src/Indicator.vala

Should still work with switchboard-plug-gcc-sound

use Settings URL scheme

---

src/Widgets/DisplayWidget.vala

Switch mic position to fit in with privacy indicator

---

src/Widgets/MprisWidget.vala

These are not the exceptions you are looking for.
(since there are literally no exceptions that can be thrown inside that `try` block)

Remove unused try/catch

---

meson.build
meson/post_install.py

We made an oops and forgot to do this

Install settings schema

---

src/Services/Adapter.vala
src/Services/Device.vala
src/Services/Manager.vala
src/Services/MediaPlayer.vala
src/Services/MprisClient.vala

Replace IOError with GLib.Error

Fix warnings about IOError

---

src/Services/MprisClient.vala

MPRISClient: Remove unused properties

---

README.md
meson.build

Require wingpanel 2.1.0

---

src/Indicator.vala
src/Widgets/DisplayWidget.vala

Set disabled mic icon when appropriate

---

src/Indicator.vala
src/Widgets/DisplayWidget.vala

Middle click mute microphone

---

data/indicator.css
data/mask.gresource.xml
src/Indicator.vala
src/Widgets/DisplayWidget.vala

DisplayWidget: Animate mute icon

---

src/Services/Adapter.vala
src/Services/Device.vala
src/Services/Manager.vala
src/Services/MediaPlayer.vala
src/Services/Volume-control.vala

This fixes linting errors in the src/Services directory.
Assuming you have [vala-lint](https://github.com/elementary/vala-lint) installed locally:
```sh
io.elementary.vala-lint -d src/Services
```
Assuming you have docker installed locally:
```sh
docker run -v "$PWD":/var/opt/vala-lint elementary/docker:vala-lint io.elementary.vala-lint -d src/Services
```
This is part of the first step towards getting #113 set up.

:shirt: Lint services directory with vala-lint

---

data/sound.appdata.xml.in
meson.build

https://github.com/elementary/wingpanel-indicator-sound/compare/2.1.3...master
Where required, I've:

Release 2.1.4

---

data/sound.appdata.xml.in
meson.build
src/Widgets/MprisGui.vala

Correct mpris text to Unkown Artist

---

src/Widgets/MprisGui.vala

Get rid of some code that messes with focus, making keyboard nav possible

MprisGui: Simplify buttons

---

src/Indicator.vala
src/Widgets/MprisWidget.vala

MprisWidget: Update default player on open

---

data/indicator.css

As reported in https://github.com/elementary/wingpanel-indicator-notifications/issues/63

Indicator.css: Fix flashing animation

---

src/Widgets/MprisWidget.vala

MprisWidget: Fix duplicated default player entry

---

data/sound.appdata.xml.in
meson.build

I confirmed this works on Hera

Release 2.1.8

---

src/Widgets/PlayerRow.vala

PlayerRow: Remove superfluous "currently"

---

meson.build
src/Indicator.vala

Demo (my middle-click button is a little broken):

Add an indicator tooltip

---

src/Widgets/PlayerRow.vala

Closes https://github.com/elementary/wingpanel-indicator-sound/issues/197

Fallback to application-default-icon

---

src/Indicator.vala
src/Widgets/DisplayWidget.vala

Supersedes #88 
Extra: remove some deprecation warnings

Allow Horizontal scroll

---

src/Widgets/DeviceManagerWidget.vala

fix: https://github.com/elementary/switchboard-plug-sound/issues/202

Remove analog outputs-inputs

---

src/Widgets/Scale.vala

Animates switch when toggling mute using sound icon or indicator icon itself

Animate switch on toggle

---

src/Indicator.vala
src/Widgets/DeviceManagerWidget.vala
src/Widgets/PlayerList.vala

Creates 3px margin between ModelButtons and separators to be consistent with other indicators

Consistent margin

---

src/Indicator.vala

Bind volume step to gnome setting

---

src/Indicator.vala
src/Widgets/Scale.vala

Fixes an issue when the switch plays an animation on first opening
It would be great if it was merged before #242

Fix switch animation on first open

---

data/PlayerRow.css
data/mask.gresource.xml
src/Widgets/PlayerRow.vala

PlayerRow: use circle buttons

---

src/Widgets/PlayerRow.vala

Fixes #12
Use CSS for label styles

PlayerRow: keep label size consistent

---

data/sound.metainfo.xml.in
meson.build

Release 7.0.0

---

src/Indicator.vala

Show on lock screen

---

src/Widgets/DeviceManagerWidget.vala

Can't use `no_show_all` in Gtk4. Also can't use `get_children`. Use a revealer and simplify the reveal condition. Animations are nice anyways :)

DeviceManagerWidget: hide/show with revealer

---

src/Device.vala
src/Indicator.vala
src/Services/PulseAudioManager.vala
src/Widgets/DeviceManagerWidget.vala

use enum for direction instead of bool

Device: use PulseAudio.Direction

---

src/Indicator.vala

Fixes https://github.com/elementary/greeter/issues/829

Allow keybindings on login screen

---

src/Indicator.vala

Doesn't fix https://github.com/elementary/greeter/issues/829 on it's own but still, we shouldn't be using Bus.watch_name

Don't use Bus.watch_name
