elementary/wingpanel-indicator-sound

src/Widgets/DisplayWidget.vala

Fixes elementary/wingpanel-indicator-keyboard/issues/10

Center with respect to other widgets in the panel

---

src/Indicator.vala

Before the `display_widget` was initialized, `volume_control` was already notifying about it's changes to various properties due to assigning them first time which fired methods that wanted to update the icon of the widget but failed. The `display_widget` is now initialized in `construct` and returned immediately in `get_display_widget` method. I'm also connecting the `button_press_event` and setting up of display widget after creation of `volume_control` because this lambda and other calls could actually access it.

Fix display widget being null

---

src/Indicator.vala

This checks the media player controls box for any children. If there are, add the separator (fixes #36).
I've also renamed the separator widgets to match the spelling of `Separator`.

Don't add first separator if there are no media player controls

---

src/Indicator.vala
src/Widgets/Scale.vala

Fixes #41 
* Make `scale_widget` public get and remove `get_scale ()`
* Make `active` a public property instead of get/set methods, bind to switch and remove `get_switch ()`
* Organize
* Remove an halign that doesn't do anything since the scale is hexpanded
* Set pixel size on the icon in case of missing scaled icons
* Click the icon to mute and unmute

Click icon to mute and cleanup

---

meson.build
vapi/libcanberra-gtk3.deps
vapi/libcanberra-gtk3.vapi

Even if they both share the same API and symbols better do it the right way

Link against libcanberra-gtk3 and not libcanberra-gtk

---

src/Widgets/MprisGui.vala

Fixes an issue pointed out by translators.. I can't remember where. In many languages this "by" bit doesn't make sense and that's why we opted not to use it in AppCenter either.

Remove 'by' before artists

---

.editorconfig
src/Widgets/MprisGui.vala

* Use Gtk.Grid instead of nested boxes
* Remove an extra eventbox
* Organize
* Don't do weird stuff with sharing `btn` variables
* Move signals to the end of the `construct` block
* Remove line wrap since labels are ellipsized and they'll never be wrapped

MprisGui: Rewrite using Gtk.Grid

---

src/Widgets/MprisGui.vala

Turns out the revealer is never used, so get rid of that and make this a Grid subclass so we can pack widgets directly instead of into a grid inside a box

MprisGui: Remove unused Revealer and Box

---

src/Indicator.vala
src/Widgets/DisplayWidget.vala
src/Widgets/Scale.vala

Fixes #71 
Fixes #39 
Fixes #31 
Fixes #3 
Fixes #2 
Scroll events from the icon and the scale widgets are provided only by a surrounding event box - rather than from individual child widgets  - and smooth scrolling is enabled (but only has effect for the scale widget).  
The same function processes events from both sources to provide a volume direction change as a double between -1.0 and +1.0 allowing fine control.
To avoid fluctuations, small deltas are accumulated and rapid direction changes ignored.
The effect of the `natural_scrolling` setting is negated so that horizontal scrolling always has the expected effect on the scale.

Fix smooth scrolling and horizontal scrolling

---

src/Widgets/MprisGui.vala

While looking into https://github.com/elementary/wingpanel-indicator-sound/issues/60 I noticed that `update_from_meta` is called in rapid succession when the song is changed, this caused the art image to be loaded in rapid succession but while also cancelling the previous load attempt. This caused 6 loads and cancels before the art image was loaded successfully, causing a noticeable delay. With this PR we only update (load) the art when the url changed. 
Before:
After:

Only update art when url changed

---

src/Widgets/MprisGui.vala

Fixes: #60 
In the case of Spotify the `app_info` property was never set, never triggering setting the fallback icon.
I've also changed the default icon from `application-default-icon` to `multimedia-audio-player`, because that seemed like a better fallback.
Before:
After: 
(No clue why the order of media players suddenly changed)

Fixed music player fallback icon logic

---

src/Indicator.vala

Fixes #93 
* The appropriate natural scroll setting is used depending on source of event
* Following the advice of @donadigo

Distinguish mouse and touchpad scroll events

---

src/Widgets/DisplayWidget.vala
src/Widgets/MaxWidthLabel.vala
src/Widgets/MprisGui.vala
src/Widgets/MprisWidget.vala

This fixes linting errors in the src/Widgets directory.
Assuming you have [vala-lint](https://github.com/elementary/vala-lint) installed locally:
```sh
io.elementary.vala-lint -d src/Widgets
```
Assuming you have docker installed locally:
```sh
docker run -v "$PWD":/var/opt/vala-lint elementary/docker:vala-lint io.elementary.vala-lint -d src/Widgets
```
This is step 1 of getting #113 set up

:shirt: Lint widgets directory with vala-lint

---

src/Indicator.vala

To test locally:
```shell
docker run -v "$PWD":/app valalang/lint:latest io.elementary.vala-lint -d .
```
```shell
io.elementary.vala-lint -d .
```

indicator: lint file using vala-lint

---

data/sound.appdata.xml.in
meson.build

It's been a while, there are translation updates, we're still compatible with 5.x, and we had a nice subtle fix.
https://github.com/elementary/wingpanel-indicator-sound/compare/2.1.6...release-2.1.7

Release 2.1.7

---

src/Widgets/DeviceItem.vala

Adds middle ellipsis for long device labels.
Fixes #190

DeviceItem: Add middle ellipsize for long device labels

---

src/Widgets/PlayerRow.vala

This PR hides MPRIS players with a "Stopped" (vs "Playing" or "Paused") playback status and no desktop entry. This matches the temporary MPRIS players that browsers create when viewing content, and theoretically any app that creates a temporary MPRIS-enabled player. I don't think there's a use case for a stopped, unidentified MPRIS player, so this should be a safe patch. Let me know if you think otherwise!
[MediaPlayer2 Spec Playback Status](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Enum:Playback_Status)
Fixes #148

Hide temporary MPRIS players that are stopped

---

data/sound.appdata.xml.in

Fixes invalid HTML in appdata. Found via appdata validation.
Rendering glitch caused by invalid HTML can also be seen in the release notes for 6.0.0 on github generated by the release action.

appdata: fix HTML syntax (li tag outside ul tag)

---

src/Services/MediaPlayer.vala

Fixes #219 
We can't use `type` directly as that causes conflicts with GObject `get_type` methods. Since Vala 0.53, it has started enforcing that property names have to start with a letter.

MediaPlayer: Give type field valid name

---

src/Services/PulseAudioManager.vala

Same as https://github.com/elementary/switchboard-plug-sound/pull/219

PulseAudioManager: Provide a fallback icon in case none is available

---

src/Services/PulseAudioManager.vala

Looks like `audio-speakers` is not in the fd.o spec and in the theme we symlink it to `audio-card`

PulseAudioManager: fallback to fd.o icon name

---

src/Services/PulseAudioManager.vala

This fixes AirPods Pro showing up as "speakers"

PulseAudioManager: icon fall back to device form factor

---

debian/control

because of https://github.com/elementary/wingpanel-indicator-sound/pull/237

Control: add gnome-settings-daemon to runtime deps

---

src/Services/Volume-control.vala

Middle-clicking the microphone indicator causes monitors to also be muted.
This is confusing because if an user is recording their screen while using the indicator to mute and un-mute their microphone, the screen recording will be silent as well.
Ask me how I know. :)

volume-control: don't mute monitor sources

---

src/Widgets/PlayerList.vala

This minimal change prevents the crash described in #99
Confirmed in https://github.com/pimvullers/elementary/issues/245

Added default_player not null check to avoid crashes

---

data/io.elementary.desktop.wingpanel.sound.gschema.xml
meson.build
src/Indicator.vala
src/Services/ShellKeyGrabber.vala

Fixes https://github.com/elementary/wingpanel-indicator-sound/issues/9
Fixes https://github.com/elementary/wingpanel-indicator-sound/issues/13
Todo:

Handle keybindings and confirmation in the indicator

---

src/Widgets/PlayerRow.vala

Added new handle for albumArt from MPRIS metadata provided by Chromium based browser in a PlayerRow.
Before:
After:
Fixes #279

Fix loading albumArt from Chromium MPRIS

---

src/Widgets/Scale.vala

Scale: use GestureMultiPress instead of button release event

---

src/Widgets/PlayerRow.vala

Gdk.EventButton doesn't exist in GTK4. We don't use it here anyways

PlayerRow: remove eventbutton from raise_player

---

src/Indicator.vala
src/Widgets/Scale.vala

Use a Gtk.Adjustment to greatly simplify construction properties and prevent the indicator from reaching into the scale's internal widgets a bunch

Scale: use Gtk.Adjustment

---

src/Indicator.vala
src/Widgets/DisplayWidget.vala

* Add event box to get rid of hacky event position stuff. We can drop EventBox in GTK4
* Use Gtk.Gesture to handle middle click events
* Don't cache style context. Getting style context is deprecated

DisplayWidget: GTK4 Prep

---

src/Indicator.vala
src/Widgets/Scale.vala

* Don't send volume change feedback when we drop the mic scale. We don't send notifications when the indicator is open and there's no reason to play a sound when the mic sensitivity changes
* When the volume slider is dropped, bypass all the complicated logic and just play the sound. We know the indicator has to be open, we know we're the volume slider, just play the sound.
* Don't expose the scale widget, send a signal. I think in GTK4 we might have to do something with observing the drag controller, I'm not sure, but that should all happen internally here and we keep it simple for the indicator who just needs to  know we dropped the slider

Scale: send a signal when slider dropped

---

src/Indicator.vala
src/Widgets/Scale.vala

We change this immediate anyways, so no need to set it when we construct

Scale: don't set an icon on construct
